{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "aiostreams.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range $field, $key := .Values.externalSecret.fields }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $.Values.externalSecret.itemId }}
        property: {{ $field }}
    {{- end }}
{{- end }}
