apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: gateway
      port: {{ .Values.service.gatewayPort }}
      targetPort: gateway
    - name: swarm-tcp
      port: {{ .Values.service.swarmPort }}
      targetPort: swarm-tcp
      protocol: TCP
    - name: swarm-udp
      port: {{ .Values.service.swarmPort }}
      targetPort: swarm-udp
      protocol: UDP
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
  selector:
    app: {{ .Release.Name }}
