{{- if .Values.restartCronJob.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-restart
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-restart
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["{{ .Release.Name }}"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-restart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-restart
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-restart
{{- end }}
