apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acestreamio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tonioriol/ritchie
    targetRevision: main
    path: charts/acestreamio
    helm:
      values: |
        # Required when ghcr.io/tonioriol/acestreamio is private.
        # Created out-of-band in the cluster as: media/ghcr-pull
        imagePullSecrets:
          - name: ghcr-pull
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
