apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acexy
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: acexy=ghcr.io/tonioriol/acexy
    argocd-image-updater.argoproj.io/acexy.update-strategy: semver
    argocd-image-updater.argoproj.io/acexy.allow-tags: "regexp:^v?\\d+\\.\\d+\\.\\d+$"
    argocd-image-updater.argoproj.io/acexy.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/acexy.helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/tonioriol/ritchie
    targetRevision: main
    path: charts/acexy
    helm:
      values: |
        imagePullSecrets:
          - name: ghcr-pull
        auth:
          enabled: true
        externalDns:
          enabled: true
          hostname: ace.tonioriol.com
          target: "85e6bc75-0025-4fc3-9341-d4e517fea614.cfargotunnel.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
