apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iptv-relay
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tonioriol/ritchie
    targetRevision: main
    path: charts/iptv-relay
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  # Keep the Secret object GitOps-managed (exists + RBAC + visibility in Argo UI),
  # but explicitly ignore secret material so it can be edited in-cluster without git.
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: iptv-relay
      namespace: media
      jsonPointers:
        - /data
        - /stringData
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
