apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iptv-relay
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tonioriol/ritchie
    targetRevision: main
    path: charts/iptv-relay
    helm:
      values: |
        externalDns:
          enabled: true
          hostname: tv.tonioriol.com
          target: "85e6bc75-0025-4fc3-9341-d4e517fea614.cfargotunnel.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  # Keep the Secret object GitOps-managed (exists + RBAC + visibility in Argo UI),
  # but explicitly ignore secret material so it can be edited in-cluster without git.
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: iptv-relay
      namespace: media
      jsonPointers:
        - /data
        - /stringData
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
