apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nullclaw
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nullclaw=ghcr.io/nullclaw/nullclaw
    argocd-image-updater.argoproj.io/nullclaw.update-strategy: newest-build
    argocd-image-updater.argoproj.io/nullclaw.allow-tags: "regexp:^v\\d{4}\\.\\d+\\.\\d+$"
    argocd-image-updater.argoproj.io/nullclaw.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/nullclaw.helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/tonioriol/ritchie
    targetRevision: main
    path: charts/nullclaw
    helm:
      values: |
        env:
          # NullClaw resolves API key from provider-specific env (e.g. OPENROUTER_API_KEY)
          # then NULLCLAW_API_KEY, then API_KEY as fallback.
          NULLCLAW_GATEWAY_HOST: "::"
          NULLCLAW_GATEWAY_PORT: "3000"
          NULLCLAW_ALLOW_PUBLIC_BIND: "true"
          NULLCLAW_WORKSPACE: "/nullclaw-data/workspace"
        auth:
          externalSecret:
            enabled: true
            itemId: openclaw
            fields:
              api_key: API_KEY
              default_provider: NULLCLAW_PROVIDER
              default_model: NULLCLAW_MODEL
              api_url: NULLCLAW_API_URL
        externalDns:
          enabled: true
          hostname: claw.tonioriol.com
          target: "85e6bc75-0025-4fc3-9341-d4e517fea614.cfargotunnel.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
