apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://1password.github.io/connect-helm-charts/
    chart: connect
    targetRevision: "1.*"
    helm:
      values: |
        connect:
          credentials_base64:
        operator:
          create: false
  destination:
    server: https://kubernetes.default.svc
    namespace: 1password
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
