apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: openclaw=ghcr.io/zeroclaw-labs/zeroclaw
    argocd-image-updater.argoproj.io/openclaw.update-strategy: semver
    argocd-image-updater.argoproj.io/openclaw.allow-tags: "regexp:^v?\\d+\\.\\d+\\.\\d+$"
    argocd-image-updater.argoproj.io/openclaw.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/openclaw.helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/tonioriol/ritchie
    targetRevision: main
    path: charts/openclaw
    helm:
      values: |
        env:
          # AI provider config injected via ExternalSecret from 1Password.
          # Gateway must bind 0.0.0.0 inside the pod for the Service to reach it.
          ZEROCLAW_GATEWAY_HOST: "0.0.0.0"
          ZEROCLAW_GATEWAY_PORT: "42617"
          # State persisted on PVC
          ZEROCLAW_STATE_DIR: "/zeroclaw-data/.zeroclaw"
          ZEROCLAW_WORKSPACE_DIR: "/zeroclaw-data/workspace"
        auth:
          externalSecret:
            enabled: true
            itemId: openclaw
            fields:
              api_key: API_KEY
              default_provider: ZEROCLAW_DEFAULT_PROVIDER
              default_model: ZEROCLAW_DEFAULT_MODEL
              api_url: ZEROCLAW_API_URL
        externalDns:
          enabled: true
          hostname: claw.tonioriol.com
          target: "85e6bc75-0025-4fc3-9341-d4e517fea614.cfargotunnel.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
