apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tonioriol/ritchie
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # Allow in-cluster automation to mutate certain parts of child Applications.
  # Needed for Argo CD Image Updater when using write-back method "argocd" (no git commits).
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        # Argo CD Image Updater writes Helm overrides here.
        - /spec/source/helm/parameters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
