image:
  repository: ghcr.io/tonioriol/iptv-merger
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-pull

replicaCount: 1

service:
  port: 80
  targetPort: 8080

hostname: tv.tonioriol.com

secret:
  create: true
  name: iptv-relay

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 512Mi

externalDns:
  enabled: false
  hostname: ""
  target: ""
